stages:
  data_fix:
    cmd: python scripts/data_scripts/modify.py
    deps:
    - data/raw/googleplaystore.csv
    - scripts/data_scripts/modify.py
    outs:
    - data/stage1
  data_stand:
    cmd: python scripts/data_scripts/stand.py
    deps:
    - data/stage1/googleplaystore.csv
    - scripts/data_scripts/stand.py
    outs:
    - data/stage2
  data_round:
    cmd: python scripts/data_scripts/round.py
    deps:
    - data/stage2/googleplaystore.csv
    - scripts/data_scripts/round.py
    outs:
    - data/stage3
  split:
    cmd: python scripts/ml_scripts/train_test_split.py
    deps:
    - data/stage3/googleplaystore.csv
    - scripts/ml_scripts/train_test_split.py
    params:
    - split.split_ratio
    outs:
    - data/stage4
  train:
    cmd: python scripts/ml_scripts/dt.py
    deps:
    - data/stage4/train.csv
    - scripts/ml_scripts/dt.py
    params:
    - train.max_depth
    - train.max_features
    - train.min_samples_leaf
    outs:
    - models/model.pkl
  evaluate:
    cmd: python scripts/ml_scripts/eval.py
    deps:
    - data/stage4/test.csv
    - models/model.pkl
    - scripts/ml_scripts/eval.py
    metrics:
    - metrics/evaluation.json:
        cache: false
